apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-dotnet
  name: hello-dotnet
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-dotnet
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-dotnet
    spec:
      containers:
      - image: localhost/hello-dotnet:dev
        imagePullPolicy: Never
        name: hello-dotnet
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: DOTNET_ENVIRONMENT
          value: "Development"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-dotnet
  name: hello-dotnet
  namespace: default
spec:
  ports:
  - port: 5005
    protocol: TCP
    targetPort: 5005
    name: web
  selector:
    app: hello-dotnet
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-dotnet
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-dotnet
                port:
                  name: web