name: Update nuget dependencies
on: 
  push:
    branches:
      - "dep-update-test"


jobs:
  build:
    name: "Update all nugets to latest version"
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore

    - name: update packages
      id: update
      uses: tjololo/nuget-dependencies-update@main
      with:
        version-limit: 'minor'
        comment-updated: true
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Updated nuget dependencies"
        body: ${{ steps.update.outputs.body }}
        reviewers: tjololo
        labels: dependencies