name: Update nuget dependencies
on: 
  schedule:
    - cron: '0 8 * * 5' # every friday AM 8:00


jobs:
  build:
    name: "Update all nugets to latest version"
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore

    - name: update packages
      uses: bchir/update-nuget@V1.0.0
      with:
        searchFor: 'outdated'
        versionToSelect: 'latest'
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        title: "Updated nuget dependencies"
        reviewers: tjololo
        labels: dependencies